server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/pms_db
        username: pms_user
        password: postgres123!
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    flyway:
        enabled: true
        baseline-on-migrate: true
        user: pms_user
        password: postgres123!

aws:
    region: us-east-2
    s3:
        bucket: my-pms-bucket-2025
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key:  ${AWS_SECRET_ACCESS_KEY}

logging:
    level:
        org.flywaydb: INFO
